#Temp while repo is private
#configs:
#  credentialTemplates:
#    private-repo:
#      url: https://github.com/nvucinic/obstack
#      password: <token>
#      username: <username>
#  repositories:
#    private-repo:
#      url: https://github.com/nvucinic/obstack  
server:
  additionalApplications:
  - name: obstack
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/nvucinic/obstack
      targetRevision: HEAD
      path: apps/monitoring
    destination:
      server: https://kubernetes.default.svc
      namespace: obstack
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true