loki-stack:
  grafana:
    enabled: true
    adminPassword: lokiloki
    # dashboardsProviders:
    #  dashboardproviders.yaml:
    #    apiVersion: 1
    #    providers:
    #     - name: 'default'
    #       orgId: 1
    #       folder: ''
    #       type: file
    #       disableDeletion: false
    #       editable: true
    #       options:
    #         path: /var/lib/grafana/dashboards/default
    sidecar:
      dashboards:
       enabled: true
       label: obstack

  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: false
    server:
      persistentVolume:
        enabled: false
