loki-stack:
  grafana:
    enabled: true
    dashboardsProviders:
     dashboardproviders.yaml:
       apiVersion: 1
       providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        aws-billing:
          # Ref: https://grafana.com/dashboards/139
          gnetId: 139
          revision: 15
          datasource: Prometheus
        redis:
          # Ref: https://grafana.com/dashboards/969
          gnetId: 969
          revision: 3
          datasource: Prometheus

  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: false
    server:
      persistentVolume:
        enabled: false