loki-stack:
  grafana:
    enabled: true
    adminPassword: changeme
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: false
    server:
      persistentVolume:
        enabled: false
