loki-stack:
  grafana:
    enabled: true
    adminPassword: lokiloki
    # dashboardsProviders:
    #  dashboardproviders.yaml:
    #    apiVersion: 1
    #    providers:
    #     - name: 'default'
    #       orgId: 1
    #       folder: ''
    #       type: file
    #       disableDeletion: false
    #       editable: true
    #       options:
    #         path: /var/lib/grafana/dashboards/default
    sidecar:
      dashboards:
    # To enable sidecar
       enabled: true
    # Label key that configMaps should have in order to be mounted 
       label: grafana_dashboard
    # Folder where the configMaps are mounted in Grafana container
      folder: /tmp/dashboards
    # To enable searching configMap accross all namespaces
      searchNamespace: ALL

  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: false
    server:
      persistentVolume:
        enabled: false
