loki-stack:
  grafana:
    enabled: true
    adminPassword: changeme
    sidecar:
      dashboards:
       enabled: true
       label: grafana_dashboard
    dashboards:
      default:
        argocd-dashboard:
          file: dashboards/argocd-dashboard.json
        loki-quicksearch:
          file: dashboards/loki-quicksearch.json
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: false
    server:
      persistentVolume:
        enabled: false
