loki-stack:
  grafana:
    enabled: true
    dashboardsProviders:
     dashboardproviders.yaml:
       apiVersion: 1
       providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

     dashboards:
       loki-quicksearch:
         gnetId: 12019
         revision: 1
         datasource: loki

  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: false
    server:
      persistentVolume:
        enabled: false