#configs:
#  credentialTemplates:
#    private-repo:
#      url: https://github.com/nvucinic/obstack
#      password: <token>
#      username: <username>
#  repositories:
#    private-repo:
#      url: https://github.com/nvucinic/obstack  

metrics:
  enabled: true
dex:
  metrics:
    enabled: true
controller:
  metrics:
    enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
server:
  metrics:
    enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"